// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presenter} from '../models';

export function CompleteDailyReview():Promise<presenter.TaskResponse>;

export function GetStreak():Promise<presenter.TaskResponse>;
