// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteDailyReview() {
  return window['go']['presenter']['HabitHandler']['CompleteDailyReview']();
}

export function GetStreak() {
  return window['go']['presenter']['HabitHandler']['GetStreak']();
}

export function GetTodayReview() {
  return window['go']['presenter']['HabitHandler']['GetTodayReview']();
}
