// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteTask(arg1: string): Promise<any>;
export function CreateTask(arg1: string): Promise<any>;
export function DeleteTask(arg1: string): Promise<any>;
export function ListTasks(): Promise<any>;
export function UpdateTask(arg1: any): Promise<any>;
