// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteTask(arg1) {
  return window['go']['presenter']['TaskHandler']['CompleteTask'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['presenter']['TaskHandler']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['presenter']['TaskHandler']['DeleteTask'](arg1);
}

export function ListTasks() {
  return window['go']['presenter']['TaskHandler']['ListTasks']();
}

export function UpdateTask(arg1) {
  return window['go']['presenter']['TaskHandler']['UpdateTask'](arg1);
}
