// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presenter} from '../models';

export function CompleteTask(arg1:string):Promise<presenter.TaskResponse>;

export function CreateTask(arg1:string):Promise<presenter.TaskResponse>;

export function DeleteTask(arg1:string):Promise<presenter.TaskResponse>;

export function ListTasks():Promise<presenter.TaskResponse>;

export function UpdateTask(arg1:presenter.UpdateTaskRequest):Promise<presenter.TaskResponse>;
